spring:
  application:
    name: MyChat-Swipe
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:mychat}?currentSchema=${DATABASE_CURRENT_SCHEMA:public}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:Rts28022007}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: ${MAIN_PORT:8084}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic: ${KAFKA_NOTIFICATION_TOPIC:notification-topic}

beauty-adjust:
  likeUniversalAdjust: 0.05
  skipUniversalAdjust: 0.01
  saveBatchSize: 1000

redis-props:
  expirationHours: 24

postgres-props:
  expirationDate: 10
