spring:
  application:
    name: MyChat-Recomendation
  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics: ${KAFKA_SUBSCRIBED_TOPICS:kb-tree}
    consumer:
      group-id: 1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:mychat}?currentSchema=${DATABASE_CURRENT_SCHEMA:public}
      username: ${DATABASE_USER:postgres}
      password: ${DATABASE_PASSWORD:Rts28022007}
      driver-class-name: org.postgresql.Driver
      port: ${DATABASE_PORT:5432}
      host: ${DATABASE_HOST:localhost}
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:http://localhost:9200}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

elasticsearch-props:
  min-shard-number: 1
  max-shard-number: 5

server:
  port: ${MAIN_PORT:8083}
  tomcat:
    threads:
      max: 50
      min-spare: 20
      max-queue-capacity: 10000

